---
title: "Hormones Bar Plot"
author: "Shuying Yu"
date: "5/9/2022"
output: 
  html_document: 
    toc: yes
    toc_float: true
    code_folding: hide
---

```{r setup, include=TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE,  warning = FALSE, message = FALSE)

#Attach packages
library(tidyverse)
library(here)
library(psych)
library(RColorBrewer)
```


```{r}
#Read in the data
#df_hormones <- read_csv(here("data", "hormone_quantile_groups.csv"))
df_hormones <- read_csv(here("data", "HAS_SNAG_mastersheet_tidy.csv"))

#Subset women
df_women <- df_hormones %>% 

  #Filter if midlife and female
  filter(age_group == "Midlife", 
         sex == "Female") %>% 
  
  #Select specific columns
  #Basic demo, snag, hormones
  dplyr::select(subject_id:repo_status_spatial,
                loop_pe_rad1_m:testosterone_spatial_ng_dl) %>% 
  
  #Reorder repo status
  mutate(repo_status_scan = fct_relevel(repo_status_scan, 
                                         c("Pre", "Peri", "Post")),
         repo_status_spatial = fct_relevel(repo_status_spatial, 
                                         c("Pre", "Peri", "Post")))

```


# Estradiol

## Scan

```{r}
#Estradiol plot
ggplot(data = df_women, aes(x = repo_status_scan, 
                            y = estradiol_scan_pg_ml, 
                            fill = repo_status_scan))+
  
  #Define bar plot by mean
  geom_bar(stat="summary", fun= "mean",
           show.legend = FALSE)+ 
  
  #Add SEM errorbar
  stat_summary(geom = "errorbar", 
               fun.data = mean_se,
               width = 0.15, size = 0.7)+
  
  #Change labels
  labs(x = "Reproductive Status",
       y = expression(atop(paste(bold("17"),
                                 bold(beta),
                                 bold("-Estradiol (pg/mL)")),
                           ))) +
  
  #Change colors of bars
  #Reverse color scale
  scale_fill_brewer(palette = "RdPu",
                    direction = -1)+
  
  #Change theme
  theme_classic() +
  
  #Customize theme
  theme(axis.title = element_text(size = 11, face = "bold"), 
        axis.text = element_text(size= 10))
```

```{r}
#Check stats
describeBy(df_women$estradiol_scan_pg_ml, 
           group = df_women$repo_status_scan)

#ANOVA
aov_fit <- aov(estradiol_scan_pg_ml ~ repo_status_scan,
               data = df_women)
summary(aov_fit) #significant
TukeyHSD(aov_fit)
#all significant pairs except peri-pre (p = 0.0758)
```


## Spatial

```{r}
#Estradiol plot
ggplot(data = df_women, aes(x = repo_status_spatial, 
                            y = estradiol_spatial_pg_ml, 
                            fill = repo_status_spatial))+
  
  #Define bar plot by mean
  geom_bar(stat="summary", fun= "mean",
           show.legend = FALSE)+ 
  
  #Add SEM errorbar
  stat_summary(geom = "errorbar", 
               fun.data = mean_se,
               width = 0.15, size = 0.7)+
  
  #Change labels
  labs(x = "Reproductive Status",
       y = expression(atop(paste(bold("17"),
                                 bold(beta),
                                 bold("-Estradiol (pg/mL)")),
                           ))) +
  
  #Change colors of bars
  #Reverse color scale
  scale_fill_brewer(palette = "RdPu",
                    direction = -1)+
  
  #Change theme
  theme_classic() +
  
  #Customize theme
  theme(axis.title = element_text(size = 11, face = "bold"), 
        axis.text = element_text(size= 10))
```


```{r}
#Check stats
describeBy(df_women$estradiol_spatial_pg_ml, 
           group = df_women$repo_status_spatial)

#ANOVA
aov_fit <- aov(estradiol_spatial_pg_ml ~ repo_status_spatial,
               data = df_women)
summary(aov_fit) #significant
TukeyHSD(aov_fit)
#all significant pairs except post-peri might be marginal (p = 0.492)
```


# FSH

## Scan 

```{r}
#FSH plot
ggplot(data = df_women, aes(x = repo_status_scan, 
                            y = fsh_scan_miu_ml, 
                            fill = repo_status_scan))+
  
  #Define bar plot by mean
  geom_bar(stat="summary", fun= "mean",
           show.legend = FALSE)+ 
  
  #Add SEM errorbar
  stat_summary(geom = "errorbar", 
               fun.data = mean_se,
               width = 0.15, size = 0.7)+
  
  #Change labels
  labs(x = "Reproductive Status",
       y = "FSH (mIU/mL)\n") +
  
  #Change colors of bars
  #Reverse color scale
  scale_fill_brewer(palette = "RdPu",
                    direction = -1)+
  
  #Change theme
  theme_classic() +
  
  #Customize theme
  theme(axis.title = element_text(size = 11, face = "bold"), 
        axis.text = element_text(size= 10))
```



```{r}
#Check stats
describeBy(df_women$fsh_scan_miu_ml, 
           group = df_women$repo_status_scan)

#ANOVA
aov_fit <- aov(fsh_scan_miu_ml ~ repo_status_scan,
               data = df_women)
summary(aov_fit) #significant
TukeyHSD(aov_fit)
#all significant pairs
```

## Spatial

```{r}
#FSH plot
ggplot(data = df_women, aes(x = repo_status_spatial, 
                            y = fsh_spatial_miu_ml, 
                            fill = repo_status_spatial))+
  
  #Define bar plot by mean
  geom_bar(stat="summary", fun= "mean",
           show.legend = FALSE)+ 
  
  #Add SEM errorbar
  stat_summary(geom = "errorbar", 
               fun.data = mean_se,
               width = 0.15, size = 0.7)+
  
  #Change labels
  labs(x = "Reproductive Status",
       y = "FSH (mIU/mL)\n") +
  
  #Change colors of bars
  #Reverse color scale
  scale_fill_brewer(palette = "RdPu",
                    direction = -1)+
  
  #Change theme
  theme_classic() +
  
  #Customize theme
  theme(axis.title = element_text(size = 11, face = "bold"), 
        axis.text = element_text(size= 10))
```



```{r}
#Check stats
describeBy(df_women$fsh_spatial_miu_ml, 
           group = df_women$repo_status_spatial)

#ANOVA
aov_fit <- aov(fsh_scan_miu_ml ~ repo_status_spatial,
               data = df_women)
summary(aov_fit) #significant
TukeyHSD(aov_fit)
#all significant pairs
```



